from machine import Pin
import time
l=Pin(12,Pin.OUT)
x=Pin(14,Pin.OUT)
y=Pin(27,Pin.OUT)
z=Pin(26,Pin.OUT)
a=Pin(25,Pin.OUT)
b=Pin(33,Pin.OUT)
w=Pin(32,Pin.OUT)

while True:
    l.on()
    time.sleep(0.25)
    l.off()
    time.sleep(0.25)
    x.on()
    time.sleep(0.25)
    x.off()
    time.sleep(0.25)
    a.on()
    time.sleep(0.20)
    a.off()
    time.sleep(0.20)
    z.on()
    time.sleep(0.20)
    z.off()
    time.sleep(0.20)
    y.on()
    time.sleep(0.5)
    y.off()
    time.sleep(0.25)
    w.on()
    time.sleep(0.25 )
    w.off()
    time.sleep(0.25)
    b.on()
    time.sleep(1)
    b.off()
    time.sleep(0.25)
    a.on()
    time.sleep(0.75)
    a.off()
    time.sleep(0.25)
    l.on()
    time.sleep(0.25)
    l.off()
    time.sleep(0.25)
    x.on()
    time.sleep(0.5 )
    x.off()
    time.sleep(0.25)
    a.on()
    time.sleep(0.20)
    a.off()
    time.sleep(0.20)
    z.on()
    time.sleep(0.20)
    z.off()
    time.sleep(0.20)
    y.on()
    time.sleep(0.5)
    y.off()
    time.sleep(0.25)
    w.on()
    time.sleep(0.25 )
    w.off()
    time.sleep(0.25)
    x.on()
    time.sleep(1)
    x.off()
    time.sleep(0.25)
    
    